### ISSUE TITLE
Element Mapping with Frame

### ISSUE THREAD

**Issue by reinaldorossetti** [jeffnyman/tapestry#1]
How do I map element with frame / iframe in element?

Exemplo:
frame(:pesquisa_cliente, :name=>'principal').input(name:'codNet', id: 'pesqMestreCodCliente')

Show:
undefined method `input' for :pesquisa_cliente:Symbol (NoMethodError)

**Comment by jeffnyman** [comment]
Hmmm. Yeah, frames and iframes are interesting. You might be able to do something like this:

    class SomePage
        iframe :pesquisa_cliente, name: 'principal'
        input :something, -> { pesquisa_cliente.input(id: 'pesqMestreCodCliente') }
    end

Here I'm just using the context of a page object. An iframe element (`pesquisa_cliente`) is declared. A particular input field (`something`) is declared as existing within the context of the iframe. This means you can query and manipulate the input field as you normally would. For example:

    page = SomePage.new
    page.something.set 'some value'

I'm definitely looking to do something different with contexts like this. This is something I admittedly put on the backburner because I was working with so many single-page apps lately. But I'll actually get back on this. I'd like to do something similar to how Capybara wraps aspects in a `within` context, as just one example.

**Comment by reinaldorossetti** [comment]
Thanks very much jeffnyman, good idea "within" like capybara. I am thinking use this framework tapestry on my next project watir.

**Comment by jeffnyman** [comment]
Cool. I'll start looking into better handling of frames and iframes. You might be curious to check out my Lucid Ruby project (https://github.com/jeffnyman/lucid_ruby). That's an example project that uses Tapestry.

**Comment by jeffnyman** [comment]
Still investigating better handling for iframes but closing this as it appears to be resolved, at least for an initial implementation.
